---
kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: golang:1.13-alpine
  entrypoint:
  - /bin/sh
  commands:
  - sudo iptables -I INPUT -p tcp --dport 8087 -j ACCEPT
  - go build main.go




