---
kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: golang:1.13-alpine
  entrypoint:
  - /bin/sh
  commands:
  - go build main.go

- name: Docker build
  image: docker:dind  #选择docker:dind镜像
  commands:
  - docker -v
  - docker ps


