---
kind: pipeline
name: default

steps:
- name: build
  image: golang:alpine
  environment:
    GO111MODULE: on 
    GOPROXY: https://goproxy.cn,direct
    CGO_ENABLED: 0  
    GOOS: linux 
    GOARCH: amd64 
  commands:
    - go build main.go 