---
kind: pipeline
name: default

steps:
- name: backend
  image: golang:alpine
  environment:
    GO111MODULE: on 
    GOPROXY: https://goproxy.cn,direct
    CGO_ENABLED: 0  
    GOOS: linux 
    GOARCH: amd64 
  settings:
      port: 8087
  commands:
      - go run main.go 