---
kind: pipeline
name: default

steps:
- name: backend
  image: golang:alpine
  environment:
    GO111MODULE: on 
    GOPROXY: https://goproxy.cn,direct
    CGO_ENABLED: 0  
    GOOS: linux 
    GOARCH: amd64 
  settings:
      dockfile: ./Dockerfile
  commands:
      - docker build -t  mygorun  . 
      - docker run -d -p 8087:8087 --name mymygorun  mygorun